# Copyright © 2022, Oracle and/or its affiliates.
# All rights reserved. Licensed under the Universal Permissive License (UPL), Version 1.0 as shown at https://oss.oracle.com/licenses/upl.


title: "free tier example setup"
description: "This example stack shows how you can setup only oci free tier resources"
schemaVersion: 1.1.0
version: "20190404" 


locale: en

variableGroups:
  - title: "RM controlled Vars"
    visible: false
    variables:
      - tenancy_ocid
      - region
      - current_user_ocid
      - fingerprint
      - private_key_path
  - title: "General Setup"
    variables:
      - compartment_id
      - create_network
      - create_vm
      - create_adb
      
  - title: "Network"
    variables: 
      - vcn_display_name
      - vcn_id 
      - subnet_id

  - title: "VM"
    variables: 
      - instance_name
      - ad
      - os

  - title: "ADB"
    variables: 
      - adb_name
      - adb_workload
      - adb_password
      - adb_version


variables:
  #"RM controlled Vars"
  tenancy_ocid:
    type: string
    title: Tenancy ID
    description: OCID of the tenancy
    required: true

  region:
    type: oci:identity:region:name
    title: Region
    description: region to create resources
    required: true

  current_user_ocid:
    type: string

  fingerprint:
    type: string
    default: " "

  private_key_path:
    type: string
    default: " "

  
  compartment_id:
    type: oci:identity:compartment:id
    title: Compartment ID
    description: compartment to deploy resources in 
    required: true 
  vcn_display_name:
    type: string 
    title: VCN Name 
    description: user friendly name to refer to the vcn
    required: true

  
  ad:
    # type : oci:identity:availabilitydomain:name
    type: number
    title: Availability Domain 
    required: true
  
  os:
    title: Operating System
    type: enum
    enum:
      - Oracle Linux Cloud Developer 8
      - Oracle Linux
      - Ubuntu
      - CentOS
    default: Oracle Linux Cloud Developer 8
